language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t yycu/u-docker-fronend -f Dockerfile.dev .

script:
  - docker run yycu/u-docker-fronend npm run test -- -- coverage
